//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Ime_TakipDegerlendirmeSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Basvurular
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Basvurular()
        {
            this.Belgeler = new HashSet<Belgeler>();
        }
    
        public int ID { get; set; }
        public int BasvuruTur { get; set; }
        public int BasvuranOgrenci { get; set; }
        public int BasvuruDurumu { get; set; }
        public Nullable<int> DegerlendirenOgretmen { get; set; }
        public System.DateTime BasvuruTarih { get; set; }
        public Nullable<byte> BasariNotu { get; set; }
        public string Donem { get; set; }
        public string Firma { get; set; }
        public string TarihAraligi { get; set; }
    
        public virtual BasvuruDurum BasvuruDurum { get; set; }
        public virtual BasvuruTuru BasvuruTuru { get; set; }
        public virtual Kullanicilar Kullanicilar { get; set; }
        public virtual Kullanicilar Kullanicilar1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Belgeler> Belgeler { get; set; }
    }
}
