//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Ime_TakipDegerlendirmeSistemi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Belgeler
    {
        public int ID { get; set; }
        public string BelgeAdresi { get; set; }
        public int Basvuru { get; set; }
        public int BelgeTuru { get; set; }
    
        public virtual Basvurular Basvurular { get; set; }
        public virtual BelgeTurleri BelgeTurleri { get; set; }
    }
}
