//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Ime_TakipDegerlendirmeSistemi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;

    public partial class Komisyonlar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Komisyonlar()
        {
            this.KomisyonOgretmen = new HashSet<KomisyonOgretmen>();
        }
    
        public Nullable<int> ID { get; set; }

        [DisplayName("Komisyon Adý")]
        public string KomisyonAdi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<KomisyonOgretmen> KomisyonOgretmen { get; set; }
    }
}
