//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Ime_TakipDegerlendirmeSistemi
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel;
    using System.ComponentModel.DataAnnotations;

    public partial class Kullanicilar
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kullanicilar()
        {
            this.Basvurular = new HashSet<Basvurular>();
            this.Basvurular1 = new HashSet<Basvurular>();
            this.KomisyonOgretmen = new HashSet<KomisyonOgretmen>();
        }
    
        public int ID { get; set; }

        [RegularExpression("[0-9]{11}", ErrorMessage = "Lütfen geçerli bir TCNo girin")]
        public string TCNo { get; set; }

        [DisplayName("Adý"), Required(), MinLength(3), MaxLength(30)]
        public string Adi { get; set; }

        [DisplayName("Soyadý"), Required(), MinLength(3), MaxLength(30)]
        public string Soyadi { get; set; }

        [DisplayName("Email"), Required(), MinLength(3), MaxLength(30), DataType(DataType.EmailAddress), RegularExpression(@"^[\w-\.]+@([\w-]+\.)+[\w-]{2,4}$", ErrorMessage = "Lütfen geçerli bir email adresi girin")]
        public string Email { get; set; }

        [DisplayName("Þifre"), MinLength(3), MaxLength(100), Required(ErrorMessage = "Þifre alaný gereklidir.")]
        public string Sifre { get; set; }

        [DisplayName("Telefon"), StringLength(10), RegularExpression(@"^[\+]?[(]?[0-9]{3}[)]?[-\s\.]?[0-9]{3}[-\s\.]?[0-9]{4,6}$", ErrorMessage = "Lütfen geçerli bir telefon numarasý girin")]
        public string Telefon { get; set; }

        [DisplayName("Sýnýf")]
        public Nullable<int> Sinifi { get; set; }

        [DisplayName("Fotoðraf"), MaxLength(50)]
        public string Fotograf { get; set; }

        [DisplayName("Okul/Sicil No"), Required(), StringLength(9), RegularExpression("[0-9]{9}", ErrorMessage = "Lütfen geçerli bir okul/sicil numarasý girin")]
        public string OkulSicilNo { get; set; }

        [DisplayName("Bölüm")]
        public Nullable<int> Bolum { get; set; }

        [DisplayName("Kayýt Tarihi")]
        public Nullable<System.DateTime> KayitTarihi { get; set; }

        [DisplayName("Rol")]
        public int Rol { get; set; }


        public bool isActive { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurular { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Basvurular> Basvurular1 { get; set; }
        public virtual Bolumler Bolumler { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        
        public virtual ICollection<KomisyonOgretmen> KomisyonOgretmen { get; set; }
        public virtual Roller Roller { get; set; }
        public virtual Siniflar Siniflar { get; set; }
    }
}
