//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Staj_Ime_TakipDegerlendirmeSistemi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities1 : DbContext
    {
        public Entities1()
            : base("name=Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<BasvuruDurum> BasvuruDurum { get; set; }
        public virtual DbSet<Basvurular> Basvurular { get; set; }
        public virtual DbSet<BasvuruTuru> BasvuruTuru { get; set; }
        public virtual DbSet<Belgeler> Belgeler { get; set; }
        public virtual DbSet<BelgeTurleri> BelgeTurleri { get; set; }
        public virtual DbSet<Bolumler> Bolumler { get; set; }
        public virtual DbSet<Fakulteler> Fakulteler { get; set; }
        public virtual DbSet<Komisyonlar> Komisyonlar { get; set; }
        public virtual DbSet<KomisyonOgretmen> KomisyonOgretmen { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
        public virtual DbSet<Roller> Roller { get; set; }
        public virtual DbSet<Siniflar> Siniflar { get; set; }
    }
}
